---
title: "Great title"
author: "Gildardo Orozco, Darren Cohen"
date: "May 5, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Introduction


```{r cars}

d = read.csv("Accidental_Drug_Related_Deaths_2012-2018.csv")
dats = read.csv("C:/Users/gilda/Documents/CSUMBSpring2019/CST383/Final_Project/chsi_dataset/RISKFACTORSANDACCESSTOCARE.csv")



```

## Data exploration



```{r pressure, echo=FALSE}

par(mfrow= c(1,2))
plot(table(d$Age[d$Heroin != "Y"]), xlab = "Age", ylab = "number of deaths without Heroin", main = "Number of deaths by age", col = "green")
plot(table(d$Age[d$Heroin == "Y"]), xlab = "Age", ylab = "number of deaths with Heroin", main = "Number of deaths by age", col = "red4")

```



```{r}

num = c(21:37)
colCounts = 0;
for(n in num ){
  curr = nrow(d[d[,n] == "Y",])
  if(n == 21){
    colCounts = c(curr)
  }else if ( n == 35){
    colCounts = c(colCounts,nrow(d[d$Other != "",]))
  }else {
    colCounts = c(colCounts,curr)
  }
}

name =  names(d[,21:37])

par(las = 2,mar= c(9,4,3,1)+0.1)
plot(colCounts, xaxt = "n", ylab = "Number of deaths", xlab = "", type = "l", col = "blue", main = "Number of deaths by drug type")
axis(1, at=1:17, labels=name)

```

